In [15]:
import pandas as pd
from statsmodels.formula.api import ols
import statsmodels.api as sm

# LSOA 
# SOTON
## HES data

In [16]:
Circulatory_mth = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\HES\AllCirculatory_monthly_all.csv')

In [17]:
Circulatory_mth = Circulatory_mth[['Disease', 'year', 'month', 'lsoa11', 'n', 'DSR','lcl','ucl','score','rank','decile']].dropna()

In [35]:
Soton_Circ = Circulatory_mth.loc[Circulatory_mth['lsoa11'] == 'E01017153']

In [23]:
Soton_Circ

,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile
7112,All Circulatory,2009,6,E01017153,7.0,1610.695068,558.276733,3477.020264,43.07,3635,2
16473,All Circulatory,2010,1,E01017153,5.0,799.468689,141.352127,2099.193848,43.07,3635,2

In [19]:
Respiratory_mth = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\HES\AllRespiratory_monthly_all.csv')

In [20]:
Respiratory_mth = Respiratory_mth[['Disease', 'year', 'month', 'lsoa11', 'n', 'DSR','lcl','ucl','score','rank','decile']].dropna()

In [21]:
Soton_Resp = Respiratory_mth.loc[Respiratory_mth['lsoa11'] == 'E01017153']

In [24]:
Soton_Resp

,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile
11780,All Respiratory,2009,10,E01017153,8.0,723.704285,114.678276,1763.697632,43.07,3635,2
13123,All Respiratory,2009,11,E01017153,7.0,924.347778,223.987198,2166.344971,43.07,3635,2
30034,All Respiratory,2010,12,E01017153,6.0,844.006897,163.821167,2108.256348,43.07,3635,2
32957,All Respiratory,2011,2,E01017153,5.0,192.479034,60.353626,453.415680,43.07,3635,2
63214,All Respiratory,2013,1,E01017153,5.0,473.175629,71.647049,1266.161011,43.07,3635,2

## MAIAC AP

In [47]:
AP_Monthly = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\Monthly_PM25_LSOA.csv')

In [26]:
AP_Monthly = AP_Monthly.rename(columns={'LSOA':'lsoa11', 'value':'PM25'})

In [10]:
AP_Monthly = AP_Monthly[['time', 'lsoa11', 'PM25', 'month', 'year']].dropna()

## Regression analysis

In [28]:
MAIAC_HES_Soton_R = pd.merge(Soton_Resp, AP_Monthly, on=['lsoa11' , 'year', 'month'], how='inner')

In [30]:
MAIAC_HES_Soton_R

,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,time,PM25
0,All Respiratory,2009,10,E01017153,8.0,723.704285,114.678276,1763.697632,43.07,3635,2,24759,2009-10-31,12.313188
1,All Respiratory,2009,11,E01017153,7.0,924.347778,223.987198,2166.344971,43.07,3635,2,24760,2009-11-30,12.833878
2,All Respiratory,2010,12,E01017153,6.0,844.006897,163.821167,2108.256348,43.07,3635,2,24773,2010-12-31,14.717027
3,All Respiratory,2011,2,E01017153,5.0,192.479034,60.353626,453.415680,43.07,3635,2,24775,2011-02-28,13.413825
4,All Respiratory,2013,1,E01017153,5.0,473.175629,71.647049,1266.161011,43.07,3635,2,24798,2013-01-31,6.481873

In [31]:
MAIAC_HES_Soton_R.corr()

,year,month,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,PM25
year,1.000000,-0.862968,-0.847946,-0.649490,-0.698289,-0.584703,NaN,NaN,NaN,0.985669,-0.759185
month,-0.862968,1.000000,0.757773,0.898944,0.840360,0.874393,NaN,NaN,NaN,-0.765369,0.655144
n,-0.847946,0.757773,1.000000,0.689452,0.549416,0.653616,NaN,NaN,NaN,-0.827106,0.337737
DSR,-0.649490,0.898944,0.689452,1.000000,0.901336,0.994907,NaN,NaN,NaN,-0.527182,0.289695
lcl,-0.698289,0.840360,0.549416,0.901336,1.000000,0.863094,NaN,NaN,NaN,-0.608901,0.448893
ucl,-0.584703,0.874393,0.653616,0.994907,0.863094,1.000000,NaN,NaN,NaN,-0.452855,0.233378
score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
decile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 0,0.985669,-0.765369,-0.827106,-0.527182,-0.608901,-0.452855,NaN,NaN,NaN,1.000000,-0.748308
PM25,-0.759185,0.655144,0.337737,0.289695,0.448893,0.233378,NaN,NaN,NaN,-0.748308,1.000000

In [32]:
model = ols("DSR ~ PM25", data=MAIAC_HES_Soton_R)
results = model.fit()
results.summary()

D:\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:72: UserWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    DSR   R-squared:                       0.084
Model:                            OLS   Adj. R-squared:                 -0.221
Method:                 Least Squares   F-statistic:                    0.2748
Date:                Wed, 24 Aug 2016   Prob (F-statistic):              0.636
Time:                        19:15:01   Log-Likelihood:                -34.817
No. Observations:                   5   AIC:                             73.63
Df Residuals:                       3   BIC:                             72.85
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept    306.8139    636.787      0.482      0.663     -1719.725  2333.353
PM25          27.1695     51.826      0.524      0.636      -137.763   192.102
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.991
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.920
Skew:                          -1.041   Prob(JB):                        0.631
Kurtosis:                       2.716   Cond. No.                         53.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# BOURNEMOUTH

In [34]:
Bmth_Circ = Circulatory_mth.loc[Circulatory_mth['lsoa11'] == 'E01015315']

In [38]:
Bmth_Circ

,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile
5509,All Circulatory,2009,5,E01015315,5.0,270.068390,82.931976,639.647156,3.95,31334,10
9594,All Circulatory,2009,8,E01015315,9.0,528.581482,231.195541,1020.800598,3.95,31334,10
20261,All Circulatory,2010,4,E01015315,5.0,230.563004,74.709770,538.360107,3.95,31334,10
31035,All Circulatory,2010,12,E01015315,6.0,337.809937,121.351570,740.137390,3.95,31334,10
32328,All Circulatory,2011,1,E01015315,7.0,392.443512,144.611053,831.941711,3.95,31334,10
35036,All Circulatory,2011,3,E01015315,8.0,417.309845,174.163834,832.514160,3.95,31334,10
39128,All Circulatory,2011,6,E01015315,6.0,309.369446,109.744820,680.408325,3.95,31334,10
41835,All Circulatory,2011,8,E01015315,5.0,257.141266,80.804367,605.391907,3.95,31334,10
47280,All Circulatory,2011,12,E01015315,6.0,343.180817,124.527359,749.588257,3.95,31334,10
48632,All Circulatory,2012,1,E01015315,5.0,275.986328,88.603470,646.051819,3.95,31334,10
56793,All Circulatory,2012,7,E01015315,7.0,376.063446,147.772552,780.907227,3.95,31334,10
58179,All Circulatory,2012,8,E01015315,5.0,256.323212,78.573242,607.364563,3.95,31334,10
59541,All Circulatory,2012,9,E01015315,5.0,280.051788,87.743347,659.844849,3.95,31334,10
82573,All Circulatory,2014,2,E01015315,5.0,255.385437,80.490349,600.788635,3.95,31334,10
83934,All Circulatory,2014,3,E01015315,6.0,327.817719,119.516655,714.983337,3.95,31334,10

In [37]:
Bmth_Resp = Respiratory_mth.loc[Respiratory_mth['lsoa11'] == 'E01015315']

In [40]:
Bmth_Resp

,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile
12882,All Respiratory,2009,11,E01015315,5.0,288.887238,93.788933,674.190063,3.95,31334,10
14248,All Respiratory,2009,12,E01015315,5.0,289.138550,88.406960,685.566650,3.95,31334,10
15704,All Respiratory,2010,1,E01015315,6.0,355.459992,117.713852,797.354675,3.95,31334,10
45539,All Respiratory,2011,12,E01015315,5.0,249.314926,78.195862,587.260742,3.95,31334,10
83179,All Respiratory,2014,4,E01015315,5.0,274.900513,83.277054,653.340820,3.95,31334,10

In [41]:
MAIAC_HES_Bmth_C = pd.merge(Bmth_Circ, AP_Monthly, on=['lsoa11' , 'year', 'month'], how='inner')

In [42]:
MAIAC_HES_Bmth_R = pd.merge(Bmth_Resp, AP_Monthly, on=['lsoa11' , 'year', 'month'], how='inner')

In [43]:
MAIAC_HES_Bmth_C.corr()

,year,month,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,PM25
year,1.000000,-0.342087,-0.306666,-0.316394,-0.315187,-0.313453,NaN,NaN,NaN,0.979702,0.136698
month,-0.342087,1.000000,0.015763,0.094473,0.082277,0.116981,NaN,NaN,NaN,-0.146780,-0.384901
n,-0.306666,0.015763,1.000000,0.977751,0.988894,0.952001,NaN,NaN,NaN,-0.319458,0.234286
DSR,-0.316394,0.094473,0.977751,1.000000,0.994511,0.994241,NaN,NaN,NaN,-0.312908,0.105552
lcl,-0.315187,0.082277,0.988894,0.994511,1.000000,0.978024,NaN,NaN,NaN,-0.314239,0.166790
ucl,-0.313453,0.116981,0.952001,0.994241,0.978024,1.000000,NaN,NaN,NaN,-0.305010,0.040745
score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
decile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 0,0.979702,-0.146780,-0.319458,-0.312908,-0.314239,-0.305010,NaN,NaN,NaN,1.000000,0.061789
PM25,0.136698,-0.384901,0.234286,0.105552,0.166790,0.040745,NaN,NaN,NaN,0.061789,1.000000

In [44]:
MAIAC_HES_Bmth_R.corr()

,year,month,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,PM25
year,1.000000e+00,-0.444976,-1.617492e-01,-3.187163e-01,-3.745942e-01,-3.134202e-01,-4.903667e-14,NaN,NaN,9.798104e-01,5.581528e-01
month,-4.449759e-01,1.000000,-7.601514e-01,-7.022010e-01,-6.618880e-01,-6.900982e-01,0.000000e+00,NaN,NaN,-2.569470e-01,-5.044829e-01
n,-1.617492e-01,-0.760151,1.000000e+00,9.106598e-01,9.258452e-01,8.657581e-01,4.440892e-16,NaN,NaN,-3.442548e-01,-8.127231e-02
DSR,-3.187163e-01,-0.702201,9.106598e-01,1.000000e+00,9.854624e-01,9.935910e-01,-4.859063e-16,NaN,NaN,-5.007087e-01,1.215621e-01
lcl,-3.745942e-01,-0.661888,9.258452e-01,9.854624e-01,1.000000e+00,9.630197e-01,2.068937e-16,NaN,NaN,-5.520095e-01,4.839764e-02
ucl,-3.134202e-01,-0.690098,8.657581e-01,9.935910e-01,9.630197e-01,1.000000e+00,-1.670886e-15,NaN,NaN,-4.922914e-01,1.804396e-01
score,-4.903667e-14,0.000000,4.440892e-16,-4.859063e-16,2.068937e-16,-1.670886e-15,1.000000e+00,NaN,NaN,-8.819660e-15,-4.341640e-16
rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
decile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 0,9.798104e-01,-0.256947,-3.442548e-01,-5.007087e-01,-5.520095e-01,-4.922914e-01,-8.819660e-15,NaN,NaN,1.000000e+00,4.897057e-01
PM25,5.581528e-01,-0.504483,-8.127231e-02,1.215621e-01,4.839764e-02,1.804396e-01,-4.341640e-16,NaN,NaN,4.897057e-01,1.000000e+00

In [45]:
model = ols("DSR ~ PM25", data=MAIAC_HES_Bmth_C)
results = model.fit()
results.summary()

D:\Anaconda3\lib\site-packages\scipy\stats\stats.py:1557: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=15
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    DSR   R-squared:                       0.011
Model:                            OLS   Adj. R-squared:                 -0.065
Method:                 Least Squares   F-statistic:                    0.1465
Date:                Wed, 24 Aug 2016   Prob (F-statistic):              0.708
Time:                        19:19:42   Log-Likelihood:                -86.310
No. Observations:                  15   AIC:                             176.6
Df Residuals:                      13   BIC:                             178.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept    302.6310     59.404      5.094      0.000       174.296   430.966
PM25           1.4365      3.753      0.383      0.708        -6.672     9.545
==============================================================================
Omnibus:                        5.923   Durbin-Watson:                   2.639
Prob(Omnibus):                  0.052   Jarque-Bera (JB):                3.114
Skew:                           1.049   Prob(JB):                        0.211
Kurtosis:                       3.761   Cond. No.                         44.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
model = ols("DSR ~ PM25", data=MAIAC_HES_Bmth_R)
results = model.fit()
results.summary()

D:\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:72: UserWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    DSR   R-squared:                       0.015
Model:                            OLS   Adj. R-squared:                 -0.314
Method:                 Least Squares   F-statistic:                   0.04500
Date:                Wed, 24 Aug 2016   Prob (F-statistic):              0.846
Time:                        19:20:01   Log-Likelihood:                -24.848
No. Observations:                   5   AIC:                             53.70
Df Residuals:                       3   BIC:                             52.91
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept    271.5531     96.346      2.819      0.067       -35.063   578.170
PM25           1.7379      8.193      0.212      0.846       -24.335    27.811
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.403
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.839
Skew:                           0.988   Prob(JB):                        0.657
Kurtosis:                       2.645   Cond. No.                         56.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# MSOA

In [58]:
Circ_MSOA = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\MSOA\Circ_MSOA.csv')

In [59]:
Circ_MSOA = Circ_MSOA[['Disease', 'year', 'month', 'MSOA11CD', 'n', 'DSR','lcl','ucl','score','rank','decile']].dropna()

In [60]:
Circ_MSOA

,Disease,year,month,MSOA11CD,n,DSR,lcl,ucl,score,rank,decile
8,All Circulatory,2009,1,E02003190,5.0,887.141540,75.347672,2490.366455,71.160004,226,1
16,All Circulatory,2009,1,E02003192,7.0,216.578567,82.616661,454.142334,17.190001,16593,6
22,All Circulatory,2009,1,E02003191,6.0,191.004242,64.210968,426.672730,10.750000,23309,8
24,All Circulatory,2009,1,E02003191,5.0,257.656281,81.810043,604.937927,6.780000,28266,9
43,All Circulatory,2009,1,E02003177,10.0,771.911560,344.309540,1461.249023,8.580000,26015,8
52,All Circulatory,2009,1,E02003181,5.0,222.309463,59.031757,544.769287,13.730000,19905,7
64,All Circulatory,2009,1,E02003181,8.0,524.418579,224.591690,1036.413086,6.300000,28806,9
75,All Circulatory,2009,1,E02003180,5.0,449.909790,144.693192,1052.687012,7.950000,26806,9
87,All Circulatory,2009,1,E02006885,6.0,246.111740,86.954025,541.935486,16.980000,16769,6
89,All Circulatory,2009,1,E02006883,6.0,116.213242,35.128689,266.923706,23.700001,11619,4
95,All Circulatory,2009,1,E02003200,6.0,276.877106,100.445106,604.808228,18.100000,15796,5
100,All Circulatory,2009,1,E02003200,7.0,369.387146,147.958679,762.061340,26.160000,10203,4
108,All Circulatory,2009,1,E02003203,5.0,402.144440,127.479027,944.585693,9.380000,24992,8
109,All Circulatory,2009,1,E02003196,5.0,179.187653,58.166893,418.193542,7.530000,27330,9
113,All Circulatory,2009,1,E02003196,7.0,385.159698,153.119400,796.652588,1.970000,32630,10
115,All Circulatory,2009,1,E02003211,7.0,388.110748,149.753967,810.805054,16.540001,17167,6
117,All Circulatory,2009,1,E02003211,11.0,378.973572,133.870270,765.261169,3.750000,31521,10
118,All Circulatory,2009,1,E02003211,5.0,103.670601,32.197086,244.824814,6.520000,28575,9
124,All Circulatory,2009,1,E02003197,5.0,564.219116,177.595032,1327.769409,12.070000,21718,7
128,All Circulatory,2009,1,E02003199,6.0,432.316803,152.662826,952.104858,19.809999,14418,5
132,All Circulatory,2009,1,E02003199,7.0,333.437866,117.363068,716.618042,19.070000,14998,5
151,All Circulatory,2009,1,E02003201,5.0,327.305725,103.423401,769.454590,21.400000,13171,5
153,All Circulatory,2009,1,E02003201,9.0,564.843872,258.016724,1072.689575,23.400000,11800,4
160,All Circulatory,2009,1,E02003205,5.0,361.007843,116.507111,843.876343,13.900000,19727,7
163,All Circulatory,2009,1,E02003210,5.0,346.443298,103.384193,826.464722,8.350000,26299,9
164,All Circulatory,2009,1,E02003210,10.0,644.800171,278.741821,1234.922974,14.340000,19293,6
165,All Circulatory,2009,1,E02003210,7.0,294.776672,116.198303,611.461853,3.400000,31806,10
166,All Circulatory,2009,1,E02003204,6.0,441.925507,153.873383,977.323059,18.840000,15206,5
169,All Circulatory,2009,1,E02003210,5.0,332.191193,63.733776,862.372131,3.400000,31800,10
173,All Circulatory,2009,1,E02003206,5.0,333.898651,107.219025,781.571960,5.910000,29295,9
...,...,...,...,...,...,...,...,...,...,...,...
89138,All Circulatory,2014,6,E02004779,6.0,342.360565,114.061234,766.696594,14.630000,19010,6
89149,All Circulatory,2014,6,E02004796,5.0,227.811600,70.479431,538.529480,11.160000,22819,7
89150,All Circulatory,2014,6,E02004796,8.0,266.306519,108.162209,536.359070,6.960000,28025,9
89156,All Circulatory,2014,6,E02004795,5.0,169.445908,44.069088,417.054657,15.370000,18258,6
89159,All Circulatory,2014,6,E02004785,5.0,198.018372,61.240227,468.143768,3.240000,31915,10
89164,All Circulatory,2014,6,E02004801,6.0,321.010986,110.496811,712.290100,8.860000,25620,8
89166,All Circulatory,2014,6,E02004801,7.0,179.323181,64.591927,382.783935,7.200000,27754,9
89167,All Circulatory,2014,6,E02004799,6.0,167.849930,44.358456,397.381409,12.620000,21100,7
89170,All Circulatory,2014,6,E02004799,5.0,178.863876,33.275757,466.388245,13.640000,20000,7
89172,All Circulatory,2014,6,E02004801,6.0,245.623367,63.696232,583.768188,5.200000,30095,10
89178,All Circulatory,2014,6,E02004788,7.0,323.137421,129.021774,667.375916,12.060000,21732,7
89183,All Circulatory,2014,6,E02004790,5.0,482.691772,155.904831,1128.068604,14.650000,18993,6
89188,All Circulatory,2014,6,E02004782,5.0,238.026108,64.615105,580.498352,8.960000,25501,8
89205,All Circulatory,2014,6,E02004804,5.0,683.432251,170.181366,1697.059814,11.040000,22971,7
89207,All Circulatory,2014,6,E02004802,6.0,570.055237,207.189926,1244.506836,17.160000,16616,6
89213,All Circulatory,2014,6,E02004813,5.0,360.348755,115.819092,843.274414,21.340000,13208,5
89216,All Circulatory,2014,6,E02004808,5.0,352.792816,106.858292,838.492920,12.910000,20779,7
89248,All Circulatory,2014,6,E02004816,8.0,307.386536,128.753311,612.426636,17.139999,16630,6
89256,All Circulatory,2014,6,E02004821,5.0,285.905823,91.284752,670.266174,12.030000,21771,7
89258,All Circulatory,2014,6,E02004828,5.0,247.257263,73.810234,589.800659,6.590000,28492,9
89265,All Circulatory,2014,6,E02004818,5.0,217.890228,68.225090,513.466370,4.930000,30374,10
89270,All Circulatory,2014,6,E02004822,5.0,412.947449,127.803307,976.083313,11.500000,22390,7
89298,All Circulatory,2014,6,E02004840,8.0,359.657196,143.412247,728.924377,10.450000,23673,8
89300,All Circulatory,2014,6,E02004840,5.0,340.410431,110.444206,794.574524,12.700000,21010,7
89313,All Circulatory,2014,6,E02004830,8.0,485.482941,204.879608,964.650635,13.950000,19683,6
89363,All Circulatory,2014,6,E02004269,7.0,205.741989,79.770569,429.135681,8.090000,26637,9
89369,All Circulatory,2014,6,E02003208,7.0,473.467651,183.461929,987.754578,39.330002,4707,2
89393,All Circulatory,2014,6,E02004739,7.0,211.709351,83.044411,439.879639,6.300000,28818,9
89395,All Circulatory,2014,6,E02004748,6.0,388.304932,140.627747,848.658264,39.660000,4602,2
89406,All Circulatory,2014,6,E02003190,5.0,635.640076,190.097031,1515.550293,30.330000,8086,3

# SOTON

In [61]:
Soton_Circ = Circ_MSOA.loc[Circ_MSOA['MSOA11CD'] == 'E02003570']

In [65]:
Soton_Circ

,Disease,year,month,MSOA11CD,n,DSR,lcl,ucl,score,rank,decile
7112,All Circulatory,2009,6,E02003570,7.0,1610.695068,558.276733,3477.020264,43.070000,3635,2
16473,All Circulatory,2010,1,E02003570,5.0,799.468689,141.352127,2099.193848,43.070000,3635,2
39363,All Circulatory,2011,6,E02003570,5.0,730.441772,180.043182,1817.432983,58.910000,1026,1
46169,All Circulatory,2011,11,E02003570,5.0,219.117279,66.407608,520.706116,58.910000,1026,1
47515,All Circulatory,2011,12,E02003570,5.0,889.914368,183.669784,2284.688477,38.810001,4858,2
51652,All Circulatory,2012,3,E02003570,5.0,916.797241,121.977104,2486.500488,38.810001,4858,2
67833,All Circulatory,2013,3,E02003570,5.0,620.986450,141.826584,1567.287109,38.810001,4858,2
82824,All Circulatory,2014,2,E02003570,6.0,1171.718628,152.596863,3065.942871,38.810001,4858,2

In [66]:
AP_MSOA = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\MSOA\Monthly_PM25_MSOA.csv')

In [67]:
AP_MSOA = AP_MSOA.rename(columns={'MSOA':'MSOA11CD', 'value':'PM25'})

In [68]:
AP_MSOA[:5]

   Unnamed: 0        time   MSOA11CD       PM25  month  year
0           0  2009-01-31  E02004135  11.036351      1  2009
1           1  2009-02-28  E02004135  13.770482      2  2009
2           2  2009-03-31  E02004135  21.414093      3  2009
3           3  2009-04-30  E02004135  19.139040      4  2009
4           4  2009-05-31  E02004135  14.395774      5  2009

In [69]:
MSOA_Soton_C = pd.merge(Soton_Circ, AP_MSOA, on=['MSOA11CD', 'year', 'month'], how='inner')

In [70]:
MSOA_Soton_C

,Disease,year,month,MSOA11CD,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,time,PM25
0,All Circulatory,2009,6,E02003570,7.0,1610.695068,558.276733,3477.020264,43.070000,3635,2,8717,2009-06-30,15.142136
1,All Circulatory,2010,1,E02003570,5.0,799.468689,141.352127,2099.193848,43.070000,3635,2,8724,2010-01-31,11.687294
2,All Circulatory,2011,6,E02003570,5.0,730.441772,180.043182,1817.432983,58.910000,1026,1,8741,2011-06-30,7.554040
3,All Circulatory,2011,11,E02003570,5.0,219.117279,66.407608,520.706116,58.910000,1026,1,8746,2011-11-30,11.014686
4,All Circulatory,2011,12,E02003570,5.0,889.914368,183.669784,2284.688477,38.810001,4858,2,8747,2011-12-31,7.036934
5,All Circulatory,2012,3,E02003570,5.0,916.797241,121.977104,2486.500488,38.810001,4858,2,8750,2012-03-31,17.178705
6,All Circulatory,2013,3,E02003570,5.0,620.986450,141.826584,1567.287109,38.810001,4858,2,8762,2013-03-31,12.523170
7,All Circulatory,2014,2,E02003570,6.0,1171.718628,152.596863,3065.942871,38.810001,4858,2,8773,2014-02-28,9.741649

In [71]:
Resp_MSOA = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\MSOA\Resp_MSOA.csv')

In [72]:
Resp_MSOA = Resp_MSOA[['Disease', 'year', 'month', 'MSOA11CD', 'n', 'DSR','lcl','ucl','score','rank','decile']].dropna()

In [74]:
Resp_MSOA[:5]

,Disease,year,month,MSOA11CD,n,DSR,lcl,ucl,score,rank,decile
2,All Respiratory,2009,1,E02003187,8.0,519.371643,196.146973,1071.320923,26.400000,10063,4
3,All Respiratory,2009,1,E02003187,6.0,607.023254,197.484589,1368.225708,35.400002,5995,2
4,All Respiratory,2009,1,E02003190,5.0,469.725189,136.399750,1128.015015,45.439999,3096,1
9,All Respiratory,2009,1,E02003192,5.0,239.129227,46.085987,620.373474,29.600000,8418,3
14,All Respiratory,2009,1,E02003192,5.0,176.565018,28.419876,469.139282,44.709999,3246,1

In [75]:
Soton_Resp = Resp_MSOA.loc[Resp_MSOA['MSOA11CD'] == 'E02003570']

In [76]:
MSOA_Soton_R = pd.merge(Soton_Resp, AP_MSOA, on=['MSOA11CD', 'year', 'month'], how='inner')

In [77]:
MSOA_Soton_R

,Disease,year,month,MSOA11CD,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,time,PM25
0,All Respiratory,2009,1,E02003570,7.0,507.926605,18.095709,1376.577148,58.910000,1026,1,8712,2009-01-31,8.198294
1,All Respiratory,2009,1,E02003570,5.0,1592.745239,306.784241,4132.410645,41.400002,4094,2,8712,2009-01-31,8.198294
2,All Respiratory,2009,1,E02003570,5.0,242.721787,68.128426,587.529053,50.590000,2121,1,8712,2009-01-31,8.198294
3,All Respiratory,2009,2,E02003570,5.0,520.315674,40.616592,1467.681274,58.910000,1026,1,8713,2009-02-28,8.966503
4,All Respiratory,2009,3,E02003570,8.0,1233.148438,267.073944,2882.849854,58.910000,1026,1,8714,2009-03-31,15.217359
5,All Respiratory,2009,4,E02003570,8.0,1392.972046,337.341187,3195.602783,58.910000,1026,1,8715,2009-04-30,17.914312
6,All Respiratory,2009,5,E02003570,10.0,1292.052002,453.285797,2644.227295,58.910000,1026,1,8716,2009-05-31,11.058286
7,All Respiratory,2009,6,E02003570,5.0,584.054260,149.969437,1441.335449,50.590000,2121,1,8717,2009-06-30,15.142136
8,All Respiratory,2009,7,E02003570,6.0,693.686035,125.954178,1748.919556,58.910000,1026,1,8718,2009-07-31,17.996592
9,All Respiratory,2009,10,E02003570,8.0,723.704285,114.678276,1763.697632,43.070000,3635,2,8721,2009-10-31,11.353625
10,All Respiratory,2009,10,E02003570,6.0,708.180054,172.602081,1703.649658,58.910000,1026,1,8721,2009-10-31,11.353625
11,All Respiratory,2009,11,E02003570,7.0,924.347778,223.987198,2166.344971,43.070000,3635,2,8722,2009-11-30,13.600492
12,All Respiratory,2009,12,E02003570,5.0,242.313522,43.251415,635.444519,58.910000,1026,1,8723,2009-12-31,9.011226
13,All Respiratory,2009,12,E02003570,5.0,890.845276,-181.205322,3008.055664,38.810001,4858,2,8723,2009-12-31,9.011226
14,All Respiratory,2010,1,E02003570,5.0,405.580231,26.692268,1153.852295,58.910000,1026,1,8724,2010-01-31,11.687294
15,All Respiratory,2010,1,E02003570,7.0,690.666260,159.299789,1632.974609,50.590000,2121,1,8724,2010-01-31,11.687294
16,All Respiratory,2010,3,E02003570,8.0,955.442139,367.579102,1959.296875,38.810001,4858,2,8726,2010-03-31,7.348862
17,All Respiratory,2010,4,E02003570,5.0,763.387451,7.984067,2255.246094,38.810001,4858,2,8727,2010-04-30,14.972867
18,All Respiratory,2010,5,E02003570,5.0,516.389526,76.705933,1384.727905,58.910000,1026,1,8728,2010-05-31,8.870710
19,All Respiratory,2010,9,E02003570,5.0,265.057251,70.730774,648.835815,58.910000,1026,1,8732,2010-09-30,15.530678
20,All Respiratory,2010,10,E02003570,5.0,448.814514,79.618439,1177.945923,38.810001,4858,2,8733,2010-10-31,9.521471
21,All Respiratory,2010,11,E02003570,5.0,453.706604,61.119759,1229.032837,38.810001,4858,2,8734,2010-11-30,8.952566
22,All Respiratory,2010,12,E02003570,6.0,844.006897,163.821167,2108.256348,43.070000,3635,2,8735,2010-12-31,10.811979
23,All Respiratory,2010,12,E02003570,8.0,398.323395,34.024258,1020.412842,58.910000,1026,1,8735,2010-12-31,10.811979
24,All Respiratory,2010,12,E02003570,7.0,1376.739380,444.194183,3030.485352,41.400002,4094,2,8735,2010-12-31,10.811979
25,All Respiratory,2011,1,E02003570,5.0,878.500061,34.050694,2546.217041,41.400002,4094,2,8736,2011-01-31,8.093485
26,All Respiratory,2011,1,E02003570,5.0,1906.129761,334.129883,5010.698242,50.590000,2121,1,8736,2011-01-31,8.093485
27,All Respiratory,2011,2,E02003570,5.0,192.479034,60.353626,453.415680,43.070000,3635,2,8737,2011-02-28,11.371059
28,All Respiratory,2011,2,E02003570,6.0,424.054871,32.687561,1151.482544,58.910000,1026,1,8737,2011-02-28,11.371059
29,All Respiratory,2011,2,E02003570,5.0,1309.778320,306.901489,3290.376221,41.400002,4094,2,8737,2011-02-28,11.371059
30,All Respiratory,2011,3,E02003570,6.0,536.161194,35.186043,1467.315063,58.910000,1026,1,8738,2011-03-31,24.391239
31,All Respiratory,2011,3,E02003570,5.0,936.754944,79.401299,2629.956787,41.400002,4094,2,8738,2011-03-31,24.391239
32,All Respiratory,2011,4,E02003570,5.0,376.697113,118.269157,887.070740,41.400002,4094,2,8739,2011-04-30,14.981021
33,All Respiratory,2011,5,E02003570,5.0,420.825684,69.675659,1114.317627,58.910000,1026,1,8740,2011-05-31,15.007550
34,All Respiratory,2011,10,E02003570,6.0,1179.847656,128.546097,3133.883789,41.400002,4094,2,8745,2011-10-31,12.682423
35,All Respiratory,2011,11,E02003570,7.0,503.118561,51.037186,1304.825195,58.910000,1026,1,8746,2011-11-30,11.014686
36,All Respiratory,2011,12,E02003570,5.0,141.799210,33.550846,355.580688,58.910000,1026,1,8747,2011-12-31,7.036934
37,All Respiratory,2011,12,E02003570,6.0,1228.088501,85.950325,3350.961182,41.400002,4094,2,8747,2011-12-31,7.036934
38,All Respiratory,2011,12,E02003570,6.0,242.213318,83.398949,537.398865,38.810001,4858,2,8747,2011-12-31,7.036934
39,All Respiratory,2011,12,E02003570,5.0,308.921844,84.600670,751.937439,50.590000,2121,1,8747,2011-12-31,7.036934
40,All Respiratory,2012,3,E02003570,5.0,282.705475,-9.399550,859.588501,58.910000,1026,1,8750,2012-03-31,17.178705
41,All Respiratory,2012,3,E02003570,5.0,1277.597046,143.217728,3517.901367,41.400002,4094,2,8750,2012-03-31,17.178705
42,All Respiratory,2012,3,E02003570,5.0,581.061951,50.743866,1628.395874,50.590000,2121,1,8750,2012-03-31,17.178705
43,All Respiratory,2012,4,E02003570,6.0,1363.088013,190.729691,3542.130371,41.400002,4094,2,8751,2012-04-30,12.774809
44,All Respiratory,2012,4,E02003570,5.0,550.050049,131.282517,1377.080933,38.810001,4858,2,8751,2012-04-30,12.774809
45,All Respiratory,2012,5,E02003570,6.0,2156.756104,555.979492,5132.092285,41.400002,4094,2,8752,2012-05-31,12.483299
46,All Respiratory,2012,5,E02003570,8.0,543.136841,171.631470,1177.531982,38.810001,4858,2,8752,2012-05-31,12.483299
47,All Respiratory,2012,12,E02003570,6.0,318.545990,-3.495303,917.118652,58.910000,1026,1,8759,2012-12-31,6.396049
48,All Respiratory,2012,12,E02003570,7.0,340.773590,118.827698,734.365356,41.400002,4094,2,8759,2012-12-31,6.396049
49,All Respiratory,2013,1,E02003570,5.0,473.175629,71.647049,1266.161011,43.070000,3635,2,8760,2013-01-31,6.425612
50,All Respiratory,2013,2,E02003570,5.0,416.153778,51.751446,1135.817871,58.910000,1026,1,8761,2013-02-28,9.204684
51,All Respiratory,2013,10,E02003570,7.0,221.037460,71.127266,486.883423,58.910000,1026,1,8769,2013-10-31,9.651049
52,All Respiratory,2013,11,E02003570,6.0,297.337524,61.308372,736.040894,58.910000,1026,1,8770,2013-11-30,6.733619
53,All Respiratory,2013,11,E02003570,5.0,207.975464,61.868717,496.524078,38.810001,4858,2,8770,2013-11-30,6.733619
54,All Respiratory,2013,12,E02003570,8.0,417.323364,41.689812,1058.767822,58.910000,1026,1,8771,2013-12-31,5.555037
55,All Respiratory,2014,2,E02003570,5.0,978.837769,-106.616165,3122.518555,41.400002,4094,2,8773,2014-02-28,9.741649
56,All Respiratory,2014,5,E02003570,6.0,319.117371,93.982384,737.571899,41.400002,4094,2,8776,2014-05-31,11.621771

In [78]:
MSOA_Soton_C.corr()

,year,month,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,PM25
year,1.000000,-0.315721,-0.255329,-0.210775,-0.573127,-0.071357,-0.313836,0.398737,0.144841,0.977076,-0.127353
month,-0.315721,1.000000,-0.116913,-0.290107,0.022568,-0.379135,0.407395,-0.376525,-0.450988,-0.106480,-0.431058
n,-0.255329,-0.116913,1.000000,0.843970,0.870935,0.741289,-0.211657,0.154427,0.311086,-0.293794,0.306251
DSR,-0.210775,-0.290107,0.843970,1.000000,0.823512,0.976792,-0.518608,0.464852,0.601052,-0.285965,0.296611
lcl,-0.573127,0.022568,0.870935,0.823512,1.000000,0.685128,-0.157503,0.086494,0.284470,-0.595524,0.293416
ucl,-0.071357,-0.379135,0.741289,0.976792,0.685128,1.000000,-0.614121,0.571220,0.673064,-0.159842,0.270135
score,-0.313836,0.407395,-0.211657,-0.518608,-0.157503,-0.614121,1.000000,-0.993621,-0.977657,-0.237466,-0.332996
rank,0.398737,-0.376525,0.154427,0.464852,0.086494,0.571220,-0.993621,1.000000,0.947715,0.333361,0.296933
decile,0.144841,-0.450988,0.311086,0.601052,0.284470,0.673064,-0.977657,0.947715,1.000000,0.050594,0.388816
Unnamed: 0,0.977076,-0.106480,-0.293794,-0.285965,-0.595524,-0.159842,-0.237466,0.333361,0.050594,1.000000,-0.230171
PM25,-0.127353,-0.431058,0.306251,0.296611,0.293416,0.270135,-0.332996,0.296933,0.388816,-0.230171,1.000000

In [80]:
model = ols("DSR ~ PM25", data=MSOA_Soton_C)
results = model.fit()
results.summary()

D:\Anaconda3\lib\site-packages\scipy\stats\stats.py:1557: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    DSR   R-squared:                       0.088
Model:                            OLS   Adj. R-squared:                 -0.064
Method:                 Least Squares   F-statistic:                    0.5788
Date:                Wed, 24 Aug 2016   Prob (F-statistic):              0.476
Time:                        19:54:34   Log-Likelihood:                -58.495
No. Observations:                   8   AIC:                             121.0
Df Residuals:                       6   BIC:                             121.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept    474.2063    540.744      0.877      0.414      -848.948  1797.360
PM25          34.4529     45.286      0.761      0.476       -76.359   145.264
==============================================================================
Omnibus:                        0.067   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.967   Jarque-Bera (JB):                0.124
Skew:                           0.007   Prob(JB):                        0.940
Kurtosis:                       2.391   Cond. No.                         43.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [81]:
MSOA_Soton_R.corr()

,year,month,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,PM25
year,1.000000,-0.022642,-0.175539,-0.174525,-0.214869,-0.136988,-0.170257,0.173383,0.194651,0.970230,-0.142574
month,-0.022642,1.000000,0.197318,-0.249838,-0.133360,-0.270280,-0.010676,0.034043,0.051106,0.220155,-0.317513
n,-0.175539,0.197318,1.000000,0.186508,0.425998,0.065114,0.183780,-0.170101,-0.119738,-0.123476,-0.034100
DSR,-0.174525,-0.249838,0.186508,1.000000,0.709293,0.981165,-0.298327,0.276968,0.300270,-0.230810,0.168099
lcl,-0.214869,-0.133360,0.425998,0.709293,1.000000,0.564798,-0.151283,0.132869,0.145162,-0.241957,0.081260
ucl,-0.136988,-0.270280,0.065114,0.981165,0.564798,1.000000,-0.323014,0.301858,0.321953,-0.199136,0.171881
score,-0.170257,-0.010676,0.183780,-0.298327,-0.151283,-0.323014,1.000000,-0.994193,-0.951621,-0.168708,0.087647
rank,0.173383,0.034043,-0.170101,0.276968,0.132869,0.301858,-0.994193,1.000000,0.958904,0.177419,-0.093098
decile,0.194651,0.051106,-0.119738,0.300270,0.145162,0.321953,-0.951621,0.958904,1.000000,0.202304,-0.068158
Unnamed: 0,0.970230,0.220155,-0.123476,-0.230810,-0.241957,-0.199136,-0.168708,0.177419,0.202304,1.000000,-0.216028
PM25,-0.142574,-0.317513,-0.034100,0.168099,0.081260,0.171881,0.087647,-0.093098,-0.068158,-0.216028,1.000000

In [83]:
model = ols("DSR ~ PM25", data=MSOA_Soton_R)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    DSR   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     1.599
Date:                Wed, 24 Aug 2016   Prob (F-statistic):              0.211
Time:                        19:55:50   Log-Likelihood:                -428.74
No. Observations:                  57   AIC:                             861.5
Df Residuals:                      55   BIC:                             865.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept    491.0022    177.182      2.771      0.008       135.922   846.082
PM25          18.5439     14.663      1.265      0.211       -10.842    47.930
==============================================================================
Omnibus:                       15.259   Durbin-Watson:                   2.273
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               17.038
Skew:                           1.232   Prob(JB):                     0.000200
Kurtosis:                       4.051   Cond. No.                         35.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Bmth

In [84]:
Bmth_Circ = Circ_MSOA.loc[Circ_MSOA['MSOA11CD'] == 'E02003182']

In [86]:
MSOA_Bmth_C = pd.merge(Bmth_Circ, AP_MSOA, on=['MSOA11CD', 'year', 'month'], how='inner')

In [87]:
Bmth_Resp = Resp_MSOA.loc[Resp_MSOA['MSOA11CD'] == 'E02003182']

In [88]:
MSOA_Bmth_R = pd.merge(Bmth_Resp, AP_MSOA, on=['MSOA11CD', 'year', 'month'], how='inner')

In [89]:
MSOA_Bmth_C.corr()

,year,month,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,PM25
year,1.000000,-0.181985,-0.000774,0.025606,0.016745,0.029457,-0.203265,0.203683,0.187791,0.980579,-0.149163
month,-0.181985,1.000000,-0.019500,-0.038563,-0.015612,-0.052458,0.007972,-0.010004,0.012736,0.014398,-0.240870
n,-0.000774,-0.019500,1.000000,0.771847,0.887090,0.625111,-0.058693,0.058453,0.047586,-0.004676,0.170719
DSR,0.025606,-0.038563,0.771847,1.000000,0.972111,0.976797,0.400182,-0.401649,-0.419676,0.018347,-0.034958
lcl,0.016745,-0.015612,0.887090,0.972111,1.000000,0.899794,0.276447,-0.277210,-0.294396,0.013913,0.036471
ucl,0.029457,-0.052458,0.625111,0.976797,0.899794,1.000000,0.504854,-0.506735,-0.525073,0.019491,-0.094598
score,-0.203265,0.007972,-0.058693,0.400182,0.276447,0.504854,1.000000,-0.999879,-0.993016,-0.205106,0.014705
rank,0.203683,-0.010004,0.058453,-0.401649,-0.277210,-0.506735,-0.999879,1.000000,0.991374,0.205125,-0.016715
decile,0.187791,0.012736,0.047586,-0.419676,-0.294396,-0.525073,-0.993016,0.991374,1.000000,0.193501,0.015261
Unnamed: 0,0.980579,0.014398,-0.004676,0.018347,0.013913,0.019491,-0.205106,0.205125,0.193501,1.000000,-0.199723
PM25,-0.149163,-0.240870,0.170719,-0.034958,0.036471,-0.094598,0.014705,-0.016715,0.015261,-0.199723,1.000000

In [90]:
MSOA_Bmth_R.corr()

,year,month,n,DSR,lcl,ucl,score,rank,decile,Unnamed: 0,PM25
year,1.000000,-0.171280,-0.195580,0.249216,0.204910,0.271155,0.199330,-0.199046,-0.209953,0.980469,-0.065220
month,-0.171280,1.000000,-0.733741,-0.037513,-0.066568,0.018997,0.252964,-0.253177,-0.242536,0.025834,-0.467417
n,-0.195580,-0.733741,1.000000,0.229570,0.397839,0.116969,-0.291006,0.290920,0.292770,-0.344920,-0.043994
DSR,0.249216,-0.037513,0.229570,1.000000,0.938107,0.990605,0.591098,-0.589968,-0.634527,0.245382,-0.260462
lcl,0.204910,-0.066568,0.397839,0.938107,1.000000,0.885793,0.408688,-0.408092,-0.431021,0.194626,-0.378342
ucl,0.271155,0.018997,0.116969,0.990605,0.885793,1.000000,0.651970,-0.650707,-0.700591,0.278923,-0.223940
score,0.199330,0.252964,-0.291006,0.591098,0.408688,0.651970,1.000000,-0.999997,-0.993973,0.252751,0.177967
rank,-0.199046,-0.253177,0.290920,-0.589968,-0.408092,-0.650707,-0.999997,1.000000,0.993682,-0.252504,-0.178509
decile,-0.209953,-0.242536,0.292770,-0.634527,-0.431021,-0.700591,-0.993973,0.993682,1.000000,-0.261447,-0.154268
Unnamed: 0,0.980469,0.025834,-0.344920,0.245382,0.194626,0.278923,0.252751,-0.252504,-0.261447,1.000000,-0.159484
PM25,-0.065220,-0.467417,-0.043994,-0.260462,-0.378342,-0.223940,0.177967,-0.178509,-0.154268,-0.159484,1.000000

In [91]:
model = ols("DSR ~ PM25", data=MSOA_Bmth_C)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    DSR   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.021
Method:                 Least Squares   F-statistic:                   0.05384
Date:                Wed, 24 Aug 2016   Prob (F-statistic):              0.818
Time:                        20:02:58   Log-Likelihood:                -288.31
No. Observations:                  46   AIC:                             580.6
Df Residuals:                      44   BIC:                             584.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept    425.8276     59.544      7.151      0.000       305.825   545.831
PM25          -0.8937      3.852     -0.232      0.818        -8.656     6.869
==============================================================================
Omnibus:                        9.210   Durbin-Watson:                   1.952
Prob(Omnibus):                  0.010   Jarque-Bera (JB):                8.633
Skew:                           1.027   Prob(JB):                       0.0133
Kurtosis:                       3.536   Cond. No.                         48.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [92]:
model = ols("DSR ~ PM25", data=MSOA_Bmth_R)
results = model.fit()
results.summary()

D:\Anaconda3\lib\site-packages\scipy\stats\stats.py:1557: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    DSR   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                 -0.088
Method:                 Least Squares   F-statistic:                    0.4367
Date:                Wed, 24 Aug 2016   Prob (F-statistic):              0.533
Time:                        20:02:59   Log-Likelihood:                -43.577
No. Observations:                   8   AIC:                             91.15
Df Residuals:                       6   BIC:                             91.31
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept    392.7998    112.336      3.497      0.013       117.923   667.677
PM25          -6.2006      9.383     -0.661      0.533       -29.161    16.760
==============================================================================
Omnibus:                        0.492   Durbin-Watson:                   2.934
Prob(Omnibus):                  0.782   Jarque-Bera (JB):                0.173
Skew:                           0.289   Prob(JB):                        0.917
Kurtosis:                       2.571   Cond. No.                         59.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""