In [1]:
import pandas as pd
from statsmodels.formula.api import ols

# Nomenclature
- DSR- Age-standardised rate for hospital admissions
- lcl- Lower Confidence limit
- ucl- Upper Confidence limit
- score- Index of Multiple Deprivation Score
- rank- Index of Multiple Deprivation Rank
- decile- Index of Multiple Deprivation Decile

# Import monthly data

In [25]:
Circulatory_monthly = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\HES\Circul_AP_monthly.csv')

In [26]:
Circulatory_monthly[:5]

,Unnamed: 0,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile,time,PM25
0,0,All Circulatory,2009,1,E01015272,NaN,69.247604,8.247776,250.557617,11.430000,22492,7,2009-01-31,11.609479
1,1,All Circulatory,2009,1,E01015273,NaN,147.841522,3.743035,823.720154,33.619999,6665,3,2009-01-31,11.410336
2,2,All Circulatory,2009,1,E01015274,NaN,187.446503,38.159660,549.000244,20.290001,13991,5,2009-01-31,11.650494
3,3,All Circulatory,2009,1,E01015275,NaN,309.000488,59.781487,912.577209,19.780001,14447,5,2009-01-31,11.682238
4,4,All Circulatory,2009,1,E01015276,NaN,162.742996,15.881656,599.259460,26.400000,10063,4,2009-01-31,11.347145

In [29]:
Circulatory_monthly.sort_values(by=['lsoa11', 'month'])

,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile,PM25
0,All Circulatory,2009,1,E01015272,NaN,69.247604,8.247776,250.557617,11.43,22492,7,11.609479
16177,All Circulatory,2010,1,E01015272,5.0,241.976242,70.326897,580.969360,11.43,22492,7,7.773952
32275,All Circulatory,2011,1,E01015272,7.0,279.166046,105.382019,587.349121,11.43,22492,7,12.289507
48580,All Circulatory,2012,1,E01015272,NaN,81.278610,7.095783,301.772492,11.43,22492,7,11.191071
64826,All Circulatory,2013,1,E01015272,7.0,274.876404,105.999260,574.357727,11.43,22492,7,8.566266
81102,All Circulatory,2014,1,E01015272,NaN,93.632965,19.309376,273.635223,11.43,22492,7,9.661566
1386,All Circulatory,2009,2,E01015272,NaN,175.643570,45.278656,455.247192,11.43,22492,7,16.521988
17519,All Circulatory,2010,2,E01015272,NaN,97.066406,9.163821,358.339569,11.43,22492,7,19.779760
33636,All Circulatory,2011,2,E01015272,5.0,225.763138,63.602028,546.017761,11.43,22492,7,13.688326
49971,All Circulatory,2012,2,E01015272,NaN,144.221191,35.706711,376.960510,11.43,22492,7,14.836639
82499,All Circulatory,2014,2,E01015272,NaN,126.375916,24.331705,373.514008,11.43,22492,7,13.267130
2738,All Circulatory,2009,3,E01015272,NaN,197.819809,51.167316,512.356628,11.43,22492,7,24.719713
18850,All Circulatory,2010,3,E01015272,6.0,257.515595,91.529587,566.030945,11.43,22492,7,13.292311
34983,All Circulatory,2011,3,E01015272,5.0,247.934647,64.806206,609.598022,11.43,22492,7,34.112225
51349,All Circulatory,2012,3,E01015272,NaN,114.718948,20.660751,342.515930,11.43,22492,7,21.788055
67517,All Circulatory,2013,3,E01015272,NaN,87.741447,7.648025,325.803406,11.43,22492,7,26.855774
83862,All Circulatory,2014,3,E01015272,NaN,57.326302,6.942479,207.082321,11.43,22492,7,22.877888
4119,All Circulatory,2009,4,E01015272,NaN,98.909904,10.328303,362.201324,11.43,22492,7,13.966952
20209,All Circulatory,2010,4,E01015272,8.0,376.005707,149.902924,762.106445,11.43,22492,7,18.364841
36367,All Circulatory,2011,4,E01015272,NaN,110.746925,20.999685,328.103333,11.43,22492,7,18.110867
52716,All Circulatory,2012,4,E01015272,NaN,160.966705,24.176813,492.254425,11.43,22492,7,16.828392
68891,All Circulatory,2013,4,E01015272,NaN,98.609253,11.886340,356.376068,11.43,22492,7,9.966362
85245,All Circulatory,2014,4,E01015272,5.0,183.702210,56.000469,435.902466,11.43,22492,7,13.132734
5470,All Circulatory,2009,5,E01015272,NaN,190.333740,47.628372,496.404877,11.43,22492,7,14.851036
21541,All Circulatory,2010,5,E01015272,7.0,320.955627,125.053787,668.361694,11.43,22492,7,11.480257
37697,All Circulatory,2011,5,E01015272,NaN,56.695187,1.435397,315.885376,11.43,22492,7,13.034283
54059,All Circulatory,2012,5,E01015272,6.0,298.927551,99.876884,668.899597,11.43,22492,7,13.291565
70249,All Circulatory,2013,5,E01015272,NaN,56.179775,1.422348,313.013672,11.43,22492,7,12.024889
86625,All Circulatory,2014,5,E01015272,NaN,80.599800,7.981761,296.442657,11.43,22492,7,11.686646
6824,All Circulatory,2009,6,E01015272,NaN,117.991608,14.289034,426.227142,11.43,22492,7,15.499490
...,...,...,...,...,...,...,...,...,...,...,...,...
56724,All Circulatory,2012,6,E01033384,NaN,100.321030,12.149341,362.394043,7.95,26801,9,23.041363
72962,All Circulatory,2013,6,E01033384,NaN,121.274155,13.107690,442.777710,7.95,26801,9,10.300530
89375,All Circulatory,2014,6,E01033384,NaN,168.599793,34.129883,494.268799,7.95,26801,9,15.409837
9543,All Circulatory,2009,7,E01033384,NaN,256.723144,67.480217,662.606934,7.95,26801,9,13.207088
25558,All Circulatory,2010,7,E01033384,NaN,62.421974,1.580390,347.792969,7.95,26801,9,11.383171
41782,All Circulatory,2011,7,E01033384,NaN,120.570732,12.284689,442.429718,7.95,26801,9,19.013760
58109,All Circulatory,2012,7,E01033384,NaN,177.276138,35.164768,521.451782,7.95,26801,9,9.831959
74310,All Circulatory,2013,7,E01033384,NaN,122.833748,14.483962,444.882202,7.95,26801,9,14.623461
10867,All Circulatory,2009,8,E01033384,NaN,141.826401,17.169964,512.343201,7.95,26801,9,13.455544
26920,All Circulatory,2010,8,E01033384,NaN,113.399918,13.729059,409.651977,7.95,26801,9,15.352480
59467,All Circulatory,2012,8,E01033384,NaN,50.160515,1.269953,279.476502,7.95,26801,9,13.528056
75653,All Circulatory,2013,8,E01033384,NaN,50.160515,1.269953,279.476502,7.95,26801,9,12.760908
28289,All Circulatory,2010,9,E01033384,NaN,218.596771,58.443573,562.089600,7.95,26801,9,13.634810
44505,All Circulatory,2011,9,E01033384,NaN,130.581024,15.024712,474.049469,7.95,26801,9,13.386116
60814,All Circulatory,2012,9,E01033384,NaN,107.051422,12.778659,387.258697,7.95,26801,9,11.343671
13506,All Circulatory,2009,10,E01033384,NaN,125.034256,14.310206,454.139740,7.95,26801,9,10.269573
29628,All Circulatory,2010,10,E01033384,NaN,107.009102,11.662002,390.409637,7.95,26801,9,9.528063
45864,All Circulatory,2011,10,E01033384,NaN,158.590408,31.661076,465.997101,7.95,26801,9,12.941363
62167,All Circulatory,2012,10,E01033384,NaN,108.782883,12.885286,393.819641,7.95,26801,9,9.390759
78385,All Circulatory,2013,10,E01033384,NaN,164.290436,33.793438,480.337555,7.95,26801,9,11.374761
14845,All Circulatory,2009,11,E01033384,6.0,366.532989,133.204071,800.217468,7.95,26801,9,8.763731
30979,All Circulatory,2010,11,E01033384,NaN,194.014237,39.963825,567.104736,7.95,26801,9,7.984747
47226,All Circulatory,2011,11,E01033384,NaN,163.119797,33.139362,477.915863,7.95,26801,9,11.271572
63510,All Circulatory,2012,11,E01033384,NaN,42.560436,1.077536,237.131576,7.95,26801,9,6.440351
79760,All Circulatory,2013,11,E01033384,NaN,108.110657,13.019348,390.750885,7.95,26801,9,7.701131
16176,All Circulatory,2009,12,E01033384,NaN,141.826401,17.169964,512.343201,7.95,26801,9,7.605399
32274,All Circulatory,2010,12,E01033384,NaN,187.265930,38.618752,547.270447,7.95,26801,9,8.087570
48579,All Circulatory,2011,12,E01033384,NaN,203.676407,41.104370,597.405212,7.95,26801,9,6.684328
64825,All Circulatory,2012,12,E01033384,NaN,42.560436,1.077536,237.131576,7.95,26801,9,6.026381
81101,All Circulatory,2013,12,E01033384,5.0,408.497742,122.742439,972.840576,7.95,26801,9,7.387822

In [31]:
Circulatory_monthly = Circulatory_monthly[['Disease', 
                                           'year', 'month', 'lsoa11', 'n', 
                                           'DSR', 'lcl', 'ucl', 
                                           'score', 'rank', 'decile', 'PM25']]

In [32]:
Circ_month_av =  Circulatory_monthly.groupby(['lsoa11', 'month']).mean()

In [34]:
Circ_month_av[:5]

                   year         n         DSR        lcl         ucl  score  \
lsoa11    month
E01015272 1      2011.5  6.333333  173.362979  52.726852  428.106923  11.43
          2      2011.2  5.000000  153.814044  35.616584  422.015808  11.43
          3      2011.5  5.500000  160.509458  40.459061  427.231209  11.43
          4      2011.5  6.500000  171.490117  45.549089  456.157344  11.43
          5      2011.5  6.500000  167.281947  47.233092  459.834646  11.43

                    rank  decile       PM25
lsoa11    month
E01015272 1      22492.0     7.0  10.181973
          2      22492.0     7.0  15.618769
          3      22492.0     7.0  23.940994
          4      22492.0     7.0  15.061691
          5      22492.0     7.0  12.728113

In [35]:
Circ_month_av.corr()

,year,n,DSR,lcl,ucl,score,rank,decile,PM25
year,1.000000,-0.007463,-0.043182,-0.025107,-0.034210,-0.005105,0.008237,0.008503,0.088010
n,-0.007463,1.000000,0.169734,0.439138,-0.005191,-0.067148,0.061178,0.058709,0.032702
DSR,-0.043182,0.169734,1.000000,0.572208,0.870106,0.189532,-0.183811,-0.183603,-0.020998
lcl,-0.025107,0.439138,0.572208,1.000000,0.153901,0.086031,-0.093765,-0.094107,0.010684
ucl,-0.034210,-0.005191,0.870106,0.153901,1.000000,0.185218,-0.174942,-0.174266,-0.032970
score,-0.005105,-0.067148,0.189532,0.086031,0.185218,1.000000,-0.949647,-0.943648,0.065954
rank,0.008237,0.061178,-0.183811,-0.093765,-0.174942,-0.949647,1.000000,0.994075,-0.070081
decile,0.008503,0.058709,-0.183603,-0.094107,-0.174266,-0.943648,0.994075,1.000000,-0.068501
PM25,0.088010,0.032702,-0.020998,0.010684,-0.032970,0.065954,-0.070081,-0.068501,1.000000

In [36]:
Respiratory_monthly = pd.read_csv(r'D:\Annies_Dissertation\Analysis\Regression\HES\Respir_AP_monthly.csv')

In [37]:
Respiratory_monthly[:5]

,Unnamed: 0,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile,time,PM25
0,0,All Respiratory,2009,1,E01015274,NaN,78.530869,1.988227,437.546020,20.290001,13991,5,2009-01-31,11.650494
1,1,All Respiratory,2009,1,E01015275,NaN,198.915909,20.564419,729.030701,19.780001,14447,5,2009-01-31,11.682238
2,2,All Respiratory,2009,1,E01015276,8.0,519.371643,196.146973,1071.320923,26.400000,10063,4,2009-01-31,11.347145
3,3,All Respiratory,2009,1,E01015277,6.0,607.023254,197.484589,1368.225708,35.400002,5995,2,2009-01-31,11.450066
4,4,All Respiratory,2009,1,E01015279,5.0,469.725189,136.399750,1128.015015,45.439999,3096,1,2009-01-31,11.536720

In [38]:
Respiratory_monthly.sort_values(by=['lsoa11', 'month'])

,Unnamed: 0,Disease,year,month,lsoa11,n,DSR,lcl,ucl,score,rank,decile,time,PM25
15658,15658,All Respiratory,2010,1,E01015272,NaN,133.342056,4.692651,515.727112,11.43,22492,7,2010-01-31,7.773952
31221,31221,All Respiratory,2011,1,E01015272,NaN,73.771416,1.867723,411.028046,11.43,22492,7,2011-01-31,12.289507
46946,46946,All Respiratory,2012,1,E01015272,NaN,52.260254,1.323111,291.175507,11.43,22492,7,2012-01-31,11.191071
62899,62899,All Respiratory,2013,1,E01015272,NaN,38.383698,0.971791,213.860275,11.43,22492,7,2013-01-31,8.566266
78949,78949,All Respiratory,2014,1,E01015272,NaN,111.280464,2.587026,434.350342,11.43,22492,7,2014-01-31,9.661566
1435,1435,All Respiratory,2009,2,E01015272,NaN,89.174248,2.257697,496.847107,11.43,22492,7,2009-02-28,16.521988
17001,17001,All Respiratory,2010,2,E01015272,NaN,44.498833,1.126614,247.931625,11.43,22492,7,2010-02-28,19.779760
32668,32668,All Respiratory,2011,2,E01015272,NaN,312.650665,81.926590,807.502258,11.43,22492,7,2011-02-28,13.688326
64315,64315,All Respiratory,2013,2,E01015272,NaN,185.478867,29.679901,562.804138,11.43,22492,7,2013-02-28,15.102678
80327,80327,All Respiratory,2014,2,E01015272,NaN,28.663151,0.725687,159.700851,11.43,22492,7,2014-02-28,13.267130
2719,2719,All Respiratory,2009,3,E01015272,NaN,73.033707,1.849055,406.917755,11.43,22492,7,2009-03-31,24.719713
18315,18315,All Respiratory,2010,3,E01015272,NaN,53.504551,1.354623,298.108246,11.43,22492,7,2010-03-31,13.292311
33999,33999,All Respiratory,2011,3,E01015272,NaN,64.822815,1.641171,361.169617,11.43,22492,7,2011-03-31,34.112225
65705,65705,All Respiratory,2013,3,E01015272,NaN,47.536736,1.203529,264.857727,11.43,22492,7,2013-03-31,26.855774
81709,81709,All Respiratory,2014,3,E01015272,5.0,336.923462,98.418190,807.951416,11.43,22492,7,2014-03-31,22.877888
4064,4064,All Respiratory,2009,4,E01015272,NaN,55.258797,1.399032,307.882294,11.43,22492,7,2009-04-30,13.966952
19644,19644,All Respiratory,2010,4,E01015272,NaN,53.504551,1.354623,298.108246,11.43,22492,7,2010-04-30,18.364841
51089,51089,All Respiratory,2012,4,E01015272,NaN,81.191185,7.103047,301.403625,11.43,22492,7,2012-04-30,16.828392
83111,83111,All Respiratory,2014,4,E01015272,5.0,253.237381,69.747391,615.614746,11.43,22492,7,2014-04-30,13.132734
5348,5348,All Respiratory,2009,5,E01015272,NaN,36.960381,0.935759,205.930038,11.43,22492,7,2009-05-31,14.851036
52412,52412,All Respiratory,2012,5,E01015272,NaN,39.112503,0.990245,217.920914,11.43,22492,7,2012-05-31,13.291565
68465,68465,All Respiratory,2013,5,E01015272,NaN,31.210987,0.790195,173.896484,11.43,22492,7,2013-05-31,12.024889
84440,84440,All Respiratory,2014,5,E01015272,NaN,171.154602,29.759043,474.416473,11.43,22492,7,2014-05-31,11.686646
6605,6605,All Respiratory,2009,6,E01015272,NaN,36.960381,0.935759,205.930038,11.43,22492,7,2009-06-30,15.499490
85775,85775,All Respiratory,2014,6,E01015272,5.0,213.110809,64.879990,505.854279,11.43,22492,7,2014-06-30,11.985504
7848,7848,All Respiratory,2009,7,E01015272,NaN,65.742294,1.664452,366.292602,11.43,22492,7,2009-07-31,21.609333
39191,39191,All Respiratory,2011,7,E01015272,NaN,52.504463,1.329298,292.536133,11.43,22492,7,2011-07-31,14.897790
54985,54985,All Respiratory,2012,7,E01015272,NaN,29.260300,0.740808,163.027954,11.43,22492,7,2012-07-31,9.617847
70998,70998,All Respiratory,2013,7,E01015272,NaN,158.068543,27.489056,474.315430,11.43,22492,7,2013-07-31,12.690435
9066,9066,All Respiratory,2009,8,E01015272,NaN,36.960381,0.935759,205.930038,11.43,22492,7,2009-08-31,14.671386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54984,54984,All Respiratory,2012,6,E01033384,NaN,52.370975,1.325919,291.792389,7.95,26801,9,2012-06-30,23.041363
70997,70997,All Respiratory,2013,6,E01033384,NaN,149.168045,30.528736,436.497345,7.95,26801,9,2013-06-30,10.300530
87047,87047,All Respiratory,2014,6,E01033384,NaN,133.761368,16.199123,483.192047,7.95,26801,9,2014-06-30,15.409837
9065,9065,All Respiratory,2009,7,E01033384,NaN,103.375298,11.980197,375.029266,7.95,26801,9,2009-07-31,13.207088
24587,24587,All Respiratory,2010,7,E01033384,NaN,164.600800,33.704517,481.614929,7.95,26801,9,2010-07-31,11.383171
40395,40395,All Respiratory,2011,7,E01033384,NaN,127.255661,14.935826,461.104309,7.95,26801,9,2011-07-31,19.013760
56284,56284,All Respiratory,2012,7,E01033384,NaN,186.195435,37.359856,546.656250,7.95,26801,9,2012-07-31,9.831959
72285,72285,All Respiratory,2013,7,E01033384,NaN,103.861771,12.578144,375.184418,7.95,26801,9,2013-07-31,14.623461
25766,25766,All Respiratory,2010,8,E01033384,NaN,107.380653,12.800550,388.501434,7.95,26801,9,2010-08-31,15.352480
41597,41597,All Respiratory,2011,8,E01033384,NaN,57.754910,1.462227,321.789764,7.95,26801,9,2011-08-31,8.556252
57471,57471,All Respiratory,2012,8,E01033384,NaN,197.634567,36.189289,588.634460,7.95,26801,9,2012-08-31,13.528056
73462,73462,All Respiratory,2013,8,E01033384,5.0,364.012970,86.427971,912.220154,7.95,26801,9,2013-08-31,12.760908
11475,11475,All Respiratory,2009,9,E01033384,NaN,186.810120,37.593025,548.194946,7.95,26801,9,2009-09-30,13.025869
42825,42825,All Respiratory,2011,9,E01033384,NaN,105.364891,12.331923,381.887115,7.95,26801,9,2011-09-30,13.386116
58678,58678,All Respiratory,2012,9,E01033384,NaN,52.370975,1.325919,291.792389,7.95,26801,9,2012-09-30,11.343671
74746,74746,All Respiratory,2013,9,E01033384,NaN,225.135925,59.444317,580.507385,7.95,26801,9,2013-09-30,11.320148
12830,12830,All Respiratory,2009,10,E01033384,NaN,55.715481,1.410598,310.426758,7.95,26801,9,2009-10-31,10.269573
28353,28353,All Respiratory,2010,10,E01033384,NaN,114.440285,13.859256,413.397644,7.95,26801,9,2010-10-31,9.528063
44124,44124,All Respiratory,2011,10,E01033384,NaN,115.375191,13.972404,416.775055,7.95,26801,9,2011-10-31,12.941363
60022,60022,All Respiratory,2012,10,E01033384,NaN,94.931412,11.052279,344.245667,7.95,26801,9,2012-10-31,9.390759
76084,76084,All Respiratory,2013,10,E01033384,NaN,56.179775,1.422348,313.013672,7.95,26801,9,2013-10-31,11.374761
29709,29709,All Respiratory,2010,11,E01033384,NaN,157.541168,32.237915,461.009705,7.95,26801,9,2010-11-30,7.984747
45486,45486,All Respiratory,2011,11,E01033384,NaN,185.436218,11.254571,703.156921,7.95,26801,9,2011-11-30,11.271572
61411,61411,All Respiratory,2012,11,E01033384,NaN,110.993347,13.287208,401.405640,7.95,26801,9,2012-11-30,6.440351
77489,77489,All Respiratory,2013,11,E01033384,NaN,51.930885,1.314777,289.340363,7.95,26801,9,2013-11-30,7.701131
15657,15657,All Respiratory,2009,12,E01033384,NaN,172.462692,35.518291,504.124603,7.95,26801,9,2009-12-31,7.605399
31220,31220,All Respiratory,2010,12,E01033384,NaN,151.967773,30.712948,445.631531,7.95,26801,9,2010-12-31,8.087570
46945,46945,All Respiratory,2011,12,E01033384,NaN,57.754910,1.462227,321.789764,7.95,26801,9,2011-12-31,6.684328
62898,62898,All Respiratory,2012,12,E01033384,NaN,247.439636,37.755455,755.268005,7.95,26801,9,2012-12-31,6.026381
78948,78948,All Respiratory,2013,12,E01033384,NaN,163.891128,32.074883,483.133301,7.95,26801,9,2013-12-31,7.387822

In [39]:
Respiratory_monthly = Respiratory_monthly[['Disease', 
                                           'year', 'month', 'lsoa11', 'n', 
                                           'DSR', 'lcl', 'ucl', 
                                           'score', 'rank', 'decile', 'PM25']]

In [40]:
Resp_month_av = Respiratory_monthly.groupby(['lsoa11', 'month']).mean()

In [41]:
Resp_month_av[:5]

                    year    n         DSR        lcl         ucl  score  \
lsoa11    month
E01015272 1      2012.00  NaN   81.807578   2.288461  373.228256  11.43
          2      2011.40  NaN  132.093153  23.143298  454.957196  11.43
          3      2011.40  5.0  115.164254  20.893313  427.800952  11.43
          4      2011.25  5.0  110.797978  19.901023  380.752228  11.43
          5      2012.00  NaN   69.609618   8.118810  268.040977  11.43

                    rank  decile       PM25
lsoa11    month
E01015272 1      22492.0     7.0   9.896472
          2      22492.0     7.0  15.671976
          3      22492.0     7.0  24.371582
          4      22492.0     7.0  15.573230
          5      22492.0     7.0  12.963534

In [42]:
Resp_month_av.corr()

,year,n,DSR,lcl,ucl,score,rank,decile,PM25
year,1.000000,-0.021700,-0.003879,-0.002807,-0.016466,-0.025319,0.026677,0.026761,0.120477
n,-0.021700,1.000000,0.256923,0.436077,0.117850,0.112663,-0.107347,-0.105284,-0.082044
DSR,-0.003879,0.256923,1.000000,0.504432,0.874364,0.348740,-0.326478,-0.324170,-0.121017
lcl,-0.002807,0.436077,0.504432,1.000000,0.120753,0.326487,-0.307634,-0.305071,-0.127563
ucl,-0.016466,0.117850,0.874364,0.120753,1.000000,0.229757,-0.212921,-0.212198,-0.068615
score,-0.025319,0.112663,0.348740,0.326487,0.229757,1.000000,-0.949573,-0.943558,0.068612
rank,0.026677,-0.107347,-0.326478,-0.307634,-0.212921,-0.949573,1.000000,0.994076,-0.072572
decile,0.026761,-0.105284,-0.324170,-0.305071,-0.212198,-0.943558,0.994076,1.000000,-0.071069
PM25,0.120477,-0.082044,-0.121017,-0.127563,-0.068615,0.068612,-0.072572,-0.071069,1.000000